// Script to convert CSV data to TypeScript array
const fs = require('fs');
const path = require('path');

function csvToTypeScript() {
  const csvPath = path.join(__dirname, 'system-data.csv');
  const outputPath = path.join(__dirname, 'src', 'systemData.ts');
  
  try {
    const csvContent = fs.readFileSync(csvPath, 'utf-8');
    const lines = csvContent.split('\n').filter(line => line.trim());
    
    // Skip header line and empty first line
    const dataLines = lines.slice(2);
    
    const systems = dataLines.map(line => {
      const columns = line.split(',');
      if (columns.length >= 6) {
        return {
          systemName: columns[0].trim(),
          systemId: columns[1].trim(), 
          level: columns[2].trim(),
          warpRange: columns[3].trim(),
          warpRangeSH: columns[4].trim(),
          factionId: columns[5].trim()
        };
      }
      return null;
    }).filter(system => system !== null);

    const tsContent = `// Auto-generated from system-data.csv
// Do not edit this file manually - run 'node csv-to-ts.js' to regenerate

export interface SystemData {
  systemName: string;
  systemId: string;
  level: string;
  warpRange: string;
  warpRangeSH: string;
  factionId: string;
}

export const SYSTEM_DATA: SystemData[] = ${JSON.stringify(systems, null, 2)};

export const SYSTEM_DATA_MAP = new Map<string, SystemData>(
  SYSTEM_DATA.map(system => [system.systemId, system])
);
`;

    fs.writeFileSync(outputPath, tsContent);
    console.log(`✅ Successfully converted ${systems.length} systems to TypeScript`);
    console.log(`📁 Output written to: ${outputPath}`);
    
  } catch (error) {
    console.error('❌ Error converting CSV:', error.message);
  }
}

csvToTypeScript();
